services:
  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    restart: no
    tty: true
    stdin_open: true
    volumes:
      - ./kali:/tools
    networks:
      - lab-net

  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    hostname: dvwa          
    restart: no
    networks:
      lab-net:
        aliases:
          - dvwa
    ports:
      - "8081:80"

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - ./suricata/rules:/etc/suricata/rules
      - ./suricata/logs:/var/log/suricata
    command: -c /etc/suricata/suricata.yaml --af-packet=br-58e145f66d10

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml:ro,Z
    networks:
      - lab-net

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - ./suricata/logs:/var/log/suricata:ro
    networks:
      - lab-net
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - lab-net
    depends_on:
      - loki
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

networks:
  lab-net:
    driver: bridge

volumes:
  loki-data:
  grafana-data: